// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC39Jn4ld1_76ZGBiEk3J3mPkdjUEzErI',
    appId: '1:984903468041:web:c06a21a76fbd0e32ee64d8',
    messagingSenderId: '984903468041',
    projectId: 'traveltrip-d9c9d',
    authDomain: 'traveltrip-d9c9d.firebaseapp.com',
    storageBucket: 'traveltrip-d9c9d.appspot.com',
    measurementId: 'G-H1VG5NGM9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-PAWnQhGr_zI63xhgOCeTwUOFzNXCSGM',
    appId: '1:984903468041:android:2622bf6735e0fb27ee64d8',
    messagingSenderId: '984903468041',
    projectId: 'traveltrip-d9c9d',
    storageBucket: 'traveltrip-d9c9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxbNm7bbTaCEO_QV3yIl2yTRjgU812BNE',
    appId: '1:984903468041:ios:695a01d5692bea27ee64d8',
    messagingSenderId: '984903468041',
    projectId: 'traveltrip-d9c9d',
    storageBucket: 'traveltrip-d9c9d.appspot.com',
    androidClientId: '984903468041-evmj8gg68te52orqp61iqrtjedq9715h.apps.googleusercontent.com',
    iosClientId: '984903468041-2c4s8mf23o3lqhaov3s807u3vhuqfmnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelTripApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxbNm7bbTaCEO_QV3yIl2yTRjgU812BNE',
    appId: '1:984903468041:ios:695a01d5692bea27ee64d8',
    messagingSenderId: '984903468041',
    projectId: 'traveltrip-d9c9d',
    storageBucket: 'traveltrip-d9c9d.appspot.com',
    androidClientId: '984903468041-evmj8gg68te52orqp61iqrtjedq9715h.apps.googleusercontent.com',
    iosClientId: '984903468041-2c4s8mf23o3lqhaov3s807u3vhuqfmnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelTripApplication',
  );
}
